name: Test target-redshift

on:
  workflow_dispatch:
    inputs: {}

jobs:
  tests:
    runs-on: depot-ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        - "3.8"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python '${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.python-version }}'
    - name: Install Poetry
      env:
        PIP_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
      run: |
        python -m pip install --upgrade pip
        pipx install poetry
    - name: Install dependencies
      run: |
        poetry env use python${{ matrix.python-version }}
        poetry install
    - name: Run pytest
      run: |
        poetry run pytest --capture=no
    - name: Run lint
      run: |
        poetry run tox -e lint

  integration:
    runs-on: depot-ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pipx install meltano
        meltano install
    - name: smoke-test-tap
      run: meltano run tap-smoke-test target-postgres
